receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317

exporters:
  logging:
  otlp/elastic:
    endpoint: localhost:9200
    headers:
      Authorization: "Bearer 123456789"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]